services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: pg-books
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: booksdb
    ports:
      - "5432:5432"
    volumes:
      - pg-books-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booksdb"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pg-books-data:
